version: '3.3'

services:
  #postgresdb for djangoc-cms
  db:
    image: postgres
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  #django-cms
  django-cms:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: django_cms
    # environment:
    #   - DATABASE_URL
    # volumes:
    #   - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db