exclude = [
    ".env",
    ".venv",
    "**/migrations/**",
]
ignore = [
    "E501",
    "E701",
    "E713",
    "E714",
    "E731",
    "F401",
    "F403",
]
line-length = 119
select = [
    "E",
    "F",
    "W",
]
