name: Python package

on: [push]

jobs:
  docs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-20.04,
        ]
    steps:
      - name: run docs test
        run: |
          nvm install 6 && nvm use 6
          npm config set spin false
          npm install -g gulp@3.9.1
          scripts/install-npm-dependencies.sh
          gulp tests:unit
          gulp lint
