name: django CMS frontend.yml

on: [push, pull_request]

jobs:
  frontend:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [6.x, 10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm install -g gulp@3.9.1
    - run: |
          gulp tests:unit
          gulp lint
          gulp bundle
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CSS and JS
        path: |
          cms/static/cms/js/dist
          cms/static/cms/css
