name: django CMS linters.yml

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: python -Im pip install --user ruff

    - name: Run ruff
      working-directory: ./src
      run: ruff --output-format=github cms menus
