name: Create a django CMS release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to create, e.g., "3.11.1rc1"'
        required: true
        type: string
    branches:
      - 'develop*'
      - 'release/**'

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Start building version ${{ inputs.version }} from branch $GITHUB_REF
        run: ./scripts/make-release ${{ inputs.version }} $GITHUB_REF
