on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to create, e.g., "3.11.1rc1"'
        required: true
        type: string
    branches:
      - 'develop*'
      - 'release/**'

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Start the build process
        run: echo  Start building version ${ input.version } from branch ${ branch }
        run: pwd
        run: ls ./scripts
