name: New contributor message

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Hello! Thank you for your contribution! 🎉

            As it's your first contribution, be sure to check out the [contribution docs](https://docs.django-cms.org/en/latest/contributing/index.html).

            If you're a Slack user and haven't joined us, please do [here](https://www.django-cms.org/slack)!

            Welcome aboard ⛵️!

      - name: Send Discord Webhook
        uses: Ilshidur/action-discord@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            {
              "embeds": [
                {
                  "title": "New Contributor Alert",
                  "description": "A new contributor has opened a pull request!",
                  "color": 3066993,  # You can customize the color here
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "${{ github.repository }}"
                    },
                    {
                      "name": "Pull Request",
                      "value": "${{ github.event.pull_request.html_url }}"
                    },
                    {
                      "name": "Contributor",
                      "value": "${{ github.event.pull_request.user.login }}"
                    }
                  ]
                }
              ]
            }